--
-- PostgreSQL database dump
--

\restrict SQMgJ5yLTxxD8oDLISw9J3p6n26j2iXacHraY34oVivKSQyITVbJdurHO1goF6o

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'member');
  return new;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activities (
    id bigint NOT NULL,
    title text NOT NULL,
    description text,
    date timestamp with time zone,
    location text,
    image_url text,
    registration_link text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


--
-- Name: activities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaborator_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collaborator_applications (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre text NOT NULL,
    email text NOT NULL,
    telefono text NOT NULL,
    ano_ingreso integer NOT NULL,
    disponibilidad text[] NOT NULL,
    tecnologias text[] NOT NULL,
    niveles_experiencia jsonb NOT NULL,
    motivacion text NOT NULL,
    estado text DEFAULT 'pendiente'::text NOT NULL,
    notas_admin text,
    email_enviado boolean DEFAULT false
);


--
-- Name: collaborator_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collaborator_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaborator_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    title text NOT NULL,
    slug text NOT NULL,
    excerpt text,
    content text,
    image_url text,
    published boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    author_id uuid,
    category text DEFAULT 'Noticia'::text
);


--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    email text,
    full_name text,
    avatar_url text,
    role text DEFAULT 'member'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


--
-- Name: talks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.talks (
    id bigint NOT NULL,
    title text NOT NULL,
    speaker text,
    description text,
    date timestamp with time zone,
    video_url text,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


--
-- Name: talks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.talks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.talks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workshop_registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workshop_registrations (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    campus text NOT NULL,
    github_user text,
    career_level text NOT NULL,
    tech_level text NOT NULL,
    motivation text,
    attended boolean DEFAULT false
);


--
-- Name: workshop_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workshop_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workshop_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: collaborator_applications collaborator_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collaborator_applications
    ADD CONSTRAINT collaborator_applications_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: news news_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_slug_key UNIQUE (slug);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: talks talks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.talks
    ADD CONSTRAINT talks_pkey PRIMARY KEY (id);


--
-- Name: workshop_registrations workshop_registrations_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_registrations
    ADD CONSTRAINT workshop_registrations_email_key UNIQUE (email);


--
-- Name: workshop_registrations workshop_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_registrations
    ADD CONSTRAINT workshop_registrations_pkey PRIMARY KEY (id);


--
-- Name: idx_collaborator_applications_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_collaborator_applications_email ON public.collaborator_applications USING btree (email);


--
-- Name: idx_collaborator_applications_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_collaborator_applications_estado ON public.collaborator_applications USING btree (estado);


--
-- Name: news news_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id);


--
-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: activities Activities are viewable by everyone.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Activities are viewable by everyone." ON public.activities FOR SELECT USING (true);


--
-- Name: news Admins and Editors can delete news.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins and Editors can delete news." ON public.news FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'editor'::text]))))));


--
-- Name: news Admins and Editors can insert news.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins and Editors can insert news." ON public.news FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'editor'::text]))))));


--
-- Name: activities Admins and Editors can manage activities.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins and Editors can manage activities." ON public.activities USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'editor'::text]))))));


--
-- Name: talks Admins and Editors can manage talks.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins and Editors can manage talks." ON public.talks USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'editor'::text]))))));


--
-- Name: news Admins and Editors can update news.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins and Editors can update news." ON public.news FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'editor'::text]))))));


--
-- Name: workshop_registrations Enable insert for everyone; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for everyone" ON public.workshop_registrations FOR INSERT WITH CHECK (true);


--
-- Name: workshop_registrations Enable read access for admins only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for admins only" ON public.workshop_registrations FOR SELECT USING ((auth.role() = 'authenticated'::text));


--
-- Name: news News are viewable by everyone.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "News are viewable by everyone." ON public.news FOR SELECT USING (true);


--
-- Name: collaborator_applications Permitir inserción pública de solicitudes; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Permitir inserción pública de solicitudes" ON public.collaborator_applications FOR INSERT WITH CHECK (true);


--
-- Name: collaborator_applications Solo admins pueden actualizar solicitudes; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Solo admins pueden actualizar solicitudes" ON public.collaborator_applications FOR UPDATE USING ((auth.role() = 'authenticated'::text));


--
-- Name: collaborator_applications Solo admins pueden leer solicitudes; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Solo admins pueden leer solicitudes" ON public.collaborator_applications FOR SELECT USING ((auth.role() = 'authenticated'::text));


--
-- Name: talks Talks are viewable by everyone.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Talks are viewable by everyone." ON public.talks FOR SELECT USING (true);


--
-- Name: profiles Users can insert their own profile.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK ((auth.uid() = id));


--
-- Name: profiles Users can see own profile; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can see own profile" ON public.profiles FOR SELECT USING ((auth.uid() = id));


--
-- Name: profiles Users can update own profile.; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING ((auth.uid() = id));


--
-- Name: activities; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

--
-- Name: collaborator_applications; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.collaborator_applications ENABLE ROW LEVEL SECURITY;

--
-- Name: news; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: talks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.talks ENABLE ROW LEVEL SECURITY;

--
-- Name: workshop_registrations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.workshop_registrations ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict SQMgJ5yLTxxD8oDLISw9J3p6n26j2iXacHraY34oVivKSQyITVbJdurHO1goF6o

