create table workshop_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  email text not null,
  campus text not null, -- Sede (Luján, Chivilcoy, etc)
  github_user text,
  career_level text not null, -- Ingresante, Avanzado, etc
  tech_level text not null, -- Nivel de Git (1-5)
  motivation text,
  attended boolean default false -- Para tomar lista después
);

-- Habilitar seguridad (RLS) para que cualquiera pueda insertar (inscribirse) pero solo admin ver
alter table workshop_registrations enable row level security;

create policy "Enable insert for everyone" 
on workshop_registrations for insert 
with check (true);

create policy "Enable read access for admins only" 
on workshop_registrations for select 
using (auth.role() = 'authenticated'); -- Asumiendo que tus admins se loguean