-- Tabla para almacenar las solicitudes de colaboración
-- Reemplaza el formulario de Formspree por almacenamiento en BD propia
create table collaborator_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  email text not null,
  telefono text not null,
  ano_ingreso integer not null,
  disponibilidad text[] not null,           -- Array: ['mañana', 'tarde', 'noche']
  tecnologias text[] not null,              -- Array: ['react', 'nodejs', ...]
  niveles_experiencia jsonb not null,       -- JSON: {"react": "intermedio", "nodejs": "principiante"}
  motivacion text not null,
  estado text default 'pendiente' not null, -- pendiente, contactado, aceptado, rechazado
  notas_admin text,                         -- Notas internas del administrador
  email_enviado boolean default false       -- Flag para confirmar envío de notificación
);

-- Índice para búsquedas por email (evitar duplicados fácilmente)
create index idx_collaborator_applications_email on collaborator_applications (email);

-- Índice para filtrar por estado
create index idx_collaborator_applications_estado on collaborator_applications (estado);

-- Habilitar Row Level Security
alter table collaborator_applications enable row level security;

-- Política: cualquier visitante puede insertar (enviar solicitud)
create policy "Permitir inserción pública de solicitudes"
on collaborator_applications for insert
with check (true);

-- Política: solo usuarios autenticados (admins) pueden leer
create policy "Solo admins pueden leer solicitudes"
on collaborator_applications for select
using (auth.role() = 'authenticated');

-- Política: solo usuarios autenticados (admins) pueden actualizar (cambiar estado, notas)
create policy "Solo admins pueden actualizar solicitudes"
on collaborator_applications for update
using (auth.role() = 'authenticated');
