-- Tabla para almacenar las postulaciones a proyectos pagos
create table proyectos_pagos_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  email text not null,
  legajo text not null,
  area text not null,                        -- 'frontend', 'backend', 'data_analytics', 'qa'
  tecnologias text[] not null,               -- Array: ['react', 'tailwind', ...]
  portfolio_url text,                        -- Link a portfolio o GitHub
  estado text default 'pendiente' not null,  -- pendiente, contactado, aceptado, rechazado
  notas_admin text,                          -- Notas internas del administrador
  email_enviado boolean default false        -- Flag para confirmar envío de notificación
);

-- Índice para búsquedas por email (evitar duplicados)
create index idx_proyectos_pagos_applications_email on proyectos_pagos_applications (email);

-- Índice para filtrar por estado
create index idx_proyectos_pagos_applications_estado on proyectos_pagos_applications (estado);

-- Índice para filtrar por área
create index idx_proyectos_pagos_applications_area on proyectos_pagos_applications (area);

-- Habilitar Row Level Security
alter table proyectos_pagos_applications enable row level security;

-- Política: cualquier visitante puede insertar (enviar postulación)
create policy "Permitir inserción pública de postulaciones a proyectos pagos"
on proyectos_pagos_applications for insert
with check (true);

-- Política: solo usuarios autenticados (admins) pueden leer
create policy "Solo admins pueden leer postulaciones a proyectos pagos"
on proyectos_pagos_applications for select
using (auth.role() = 'authenticated');

-- Política: solo usuarios autenticados (admins) pueden actualizar
create policy "Solo admins pueden actualizar postulaciones a proyectos pagos"
on proyectos_pagos_applications for update
using (auth.role() = 'authenticated');
